### ISSUE TITLE
Not able to Login in PacBot Dashboard

### ISSUE THREAD

**Issue by c2c-engg-20170105** [tmobile/pacbot#377]
# ❔ Question
I have build source code in Development Dashboard but not able to log in using the Provided credential.

•	Admin User : admin@pacbot.org / pacman
•	Readonly User : user@pacbot.org / user

![loginFailed](https://user-images.githubusercontent.com/26300304/69329141-85483e80-0c76-11ea-8621-f2f65b4e3ecf.png)

It is giving me authentication failed error please help.

Aha! Link: https://t-mobile1t-mobile.aha.io/features/PM-534

**Comment by santhoshigorle** [comment]
can you follow steps to resolve your issue
https://github.com/tmobile/pacbot/wiki/FAQS#how-can-i-add-a-new-user-
https://github.com/tmobile/pacbot/issues/19

**Comment by c2c-engg-20170105** [comment]
Hi, I have installed PacBot successfully. But, not able to access the PacBot dashboard.
where I can check the login failed error logs?
Below you can see the services are created properly still facing the PacBot dashboard log-in issue.

![pacbot_batch](https://user-images.githubusercontent.com/26300304/70038295-03dd9e00-15de-11ea-8830-fb657a925dab.png)
![pacbot_module](https://user-images.githubusercontent.com/26300304/70038415-2e2f5b80-15de-11ea-8e43-477a3050e103.png)
![pacbot_module](https://user-images.githubusercontent.com/26300304/70038446-3e473b00-15de-11ea-8051-7edde7686e78.png)
![pacbot_success](https://user-images.githubusercontent.com/26300304/70038460-443d1c00-15de-11ea-9a5a-9e30d4c3c3bd.png)
![pacbot_db](https://user-images.githubusercontent.com/26300304/70038465-48693980-15de-11ea-9748-15f38eb9fe9a.png)

I have installed all required dependencies and use requires polices still facing login issues.
 
![pacbot_dashboard](https://user-images.githubusercontent.com/26300304/70038472-4bfcc080-15de-11ea-832f-5bec832d551d.png)

How can I solve the above issues?

**Comment by sajeer-nooh** [comment]
@c2c-engg-20170105 
Normally after installation it would take a couple of minutes for APIs to start. So even after 10-15 minutes of installation, if you are not able to login then there might be some issue.

**Steps to debug:**
1. Go to ECS-> Pacbot-> Tasks
2. Click on Config and go to the bottom of the page to see the container details
3. Click on Cloud-watch log and check if there is any error 
   (You can also directly go to the CW log streams /pacbot/apis, and check config and auth tasks log) 

If you are not finding any error in the logs, please take the url in the browser
http://{ALB domain}/api/admin/api.html
and check if you can access it or not.

**Comment by c2c-engg-20170105** [comment]
Hi , 
I have cloned the PacBot source code from the GitHub again and try to install PacBot.
It is giving error.
 
![error](https://user-images.githubusercontent.com/26300304/70140239-4ecce380-16ba-11ea-8a4c-8a5134858aea.png)

I want to check the detail error But, the error log file is not available.

Kindly please help me.

**Comment by sajeer-nooh** [comment]
Can you send me the terraform_install.log file?

**Comment by c2c-engg-20170105** [comment]
I have deleted all resources the code is working fine and error log also generating.

**Comment by sajeer-nooh** [comment]
so your problem solved?

**Comment by c2c-engg-20170105** [comment]
yes, the problem is solved...

**Comment by sajeer-nooh** [comment]
Good! 
Thank you for contacting us. Please close this issue and feel free to reopen if you find any?

**Comment by c2c-engg-20170105** [comment]
@sajeer-nooh Thank you for your reply
I have followed the below steps:
Go to ECS-> Pacbot-> Tasks
Click on Config and go to the bottom of the page to see the container details
Click on Cloud-watch log and check if there is any error
(You can also directly go to the CW log streams /pacbot/apis, and check config and auth tasks log)
If you are not finding any error in the logs, please take the url in the browser
http://{ALB domain}/api/admin/api.html 

in pacbot task, I haven't got any error.
but when I hit the http://{ALB domain}/api/admin/api.html

**Comment by santhoshigorle** [comment]
@sajeer-nooh  If she still face issue, please get into call and help her in setting up PacBot.

**Comment by sajeer-nooh** [comment]
@c2c-engg-20170105 
Are you still facing issue with login other than this, https://github.com/tmobile/pacbot/issues/393?

**Comment by c2c-engg-20170105** [comment]
> Are you still facing issue with login other than this, #393?

Yes, unable to login in pacbot dashboard

**Comment by c2c-engg-20170105** [comment]
The problem of login in dashboard is solved

**Comment by reka193** [comment]
I am facing the same issue, can you please provide some details how it was solved?
